### ISSUE TITLE
from openfold.utils.feats import atom14_to_atom37 ModuleNotFoundError: No module named 'openfold.utils.feats'

### ISSUE THREAD

**Issue by rytakahashi** [BioinfoMachineLearning/PoseBench#4] opened 2024-06-13 13:25 UTC
Hi,
Thanks for your interesting work.

First, following the instructions, when I execute EMSFold, I am getting following errors

```
python src/data/components/esmfold_batch_structure_prediction.py -i data/posebusters_benchmark_set/posebusters_benchmark_esmfold_sequences.fasta -o data/posebusters_benchmark_set/posebusters_benchmark_esmfold_structures --skip-existing
24/06/13 15:20:17 | INFO | root | Reading sequences from data/posebusters_benchmark_set/posebusters_benchmark_esmfold_sequences.fasta
24/06/13 15:20:17 | INFO | root | Loaded 4 sequences from data/posebusters_benchmark_set/posebusters_benchmark_esmfold_sequences.fasta
24/06/13 15:20:17 | INFO | root | Loading model
Traceback (most recent call last):
  File "/home/rtakahashi/software/PoseBench/src/data/components/esmfold_batch_structure_prediction.py", line 256, in <module>
    main()
  File "/home/rtakahashi/software/PoseBench/src/data/components/esmfold_batch_structure_prediction.py", line 252, in main
    run(args)
  File "/home/rtakahashi/software/PoseBench/src/data/components/esmfold_batch_structure_prediction.py", line 191, in run
    model = esm.pretrained.esmfold_v1()
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/esm/pretrained.py", line 419, in esmfold_v1
    import esm.esmfold.v1.pretrained
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/esm/esmfold/v1/pretrained.py", line 10, in <module>
    from esm.esmfold.v1.esmfold import ESMFold
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/esm/esmfold/v1/esmfold.py", line 17, in <module>
    from esm.esmfold.v1.misc import (
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/esm/esmfold/v1/misc.py", line 15, in <module>
    from openfold.utils.feats import atom14_to_atom37
ModuleNotFoundError: No module named 'openfold.utils.feats'
```
Do I missing some modules?

Many thanks,

**Comment by amorehead** [comment] 2024-06-13 20:08
Hi. Thanks for reporting this error.

Upon running `mamba env create -f environments/posebench_environment.yaml` as described in the README's `Installation` section, your local copy of `mamba` should fetch a custom fork of `openfold` I have hosted here: `git+https://github.com/amorehead/openfold.git@fe1275099639bf7e617e09ef24d6af778647dd64`.

However, it seems your installation of the `PoseBench` environment does not recognize the correct version of OpenFold for some reason. In which case, would you be able to send me the output of the command `conda activate PoseBench && mamba list | grep "openfold"` on your local machine? That should help us figure out whether or not somehow the wrong version of `openfold` was fetched by `mamba`.

**Comment by rytakahashi** [comment] 2024-06-14 17:11
Many thanks for a quick reply.
Somehow, my **evn** looks like a bit screwed.  Now, I am able to get rid of these openfold errors.

However, 
```
python3 src/data/components/esmfold_batch_structure_prediction.py -i data/astex_diverse_set/astex_diverse_esmfold_sequences.fasta -o data/astex_diverse_set/astex_diverse_esmfold_structures --skip-existing
24/06/14 18:56:01 | INFO | root | Reading sequences from data/astex_diverse_set/astex_diverse_esmfold_sequences.fasta
24/06/14 18:56:01 | INFO | root | Loaded 0 sequences from data/astex_diverse_set/astex_diverse_esmfold_sequences.fasta
24/06/14 18:56:01 | INFO | root | Loading model
[2024-06-14 18:56:03,149] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
24/06/14 18:56:43 | INFO | root | Starting Predictions
Traceback (most recent call last):
  File "/home/rtakahashi/software/PoseBench/src/data/components/esmfold_batch_structure_prediction.py", line 256, in <module>
    main()
  File "/home/rtakahashi/software/PoseBench/src/data/components/esmfold_batch_structure_prediction.py", line 252, in main
    run(args)
  File "/home/rtakahashi/software/PoseBench/src/data/components/esmfold_batch_structure_prediction.py", line 213, in run
    output = model.infer(sequences, num_recycles=args.num_recycles)
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/esm/esmfold/v1/esmfold.py", line 322, in infer
    output = self.forward(
  File "/home/rtakahashi/mambaforge/envs/PoseBench/lib/python3.10/site-packages/esm/esmfold/v1/esmfold.py", line 179, in forward
    L = aa.shape[1]
IndexError: tuple index out of range
```
Just ccheck ```astex_diverse_esmfold_sequences.fasta``` was generated correctly.

Do you have any crew? Many thanks,

**Comment by amorehead** [comment] 2024-06-15 00:23
The error above seems to suggest that somehow ESMFold's `batch_structure_prediction` script is not able to correctly read your `data/astex_diverse_set/astex_diverse_esmfold_sequences.fasta` FASTA sequence file, as it found `0 sequences` in it. This doesn't seem to me to be a Conda environment-related error. Instead, this might occur if the path to this FASTA sequence file is invalid (thereby telling the script to parse an empty file). Are you able to confirm that this FASTA file exists at `data/astex_diverse_set/astex_diverse_esmfold_sequences.fasta`?

Also, if it helps, I have uploaded to Zenodo preprocessed ESMFold-predicted structures for all 4 test datasets currently included in `PoseBench`. You should be able to directly download and use these instead of predicting the structures yourself.

**Comment by rytakahashi** [comment] 2024-06-17 13:17
Many thanks for your quick replies.

It looks like my installation was somehow screwed, I did clean checkout and installed again,
however,

after ```casp15_ligand_scoring

```conda deactivate

and at the diffdock installtion, I got following errors.
prody=2.2.0 cannot be installed?

Many thanks,

```
conda activate casp15_ligand_scoring  # NOTE: one still needs to use `conda` to (de)activate environments
pip3 install -e .
# - DiffDock environment (~13 GB)
mamba env create -f environments/diffdock_environment.yaml --prefix forks/DiffDock/DiffDock/
conda activate forks/DiffDock/DiffDock/  # NOTE: one still needs to use `conda` to (de)activate environments
```


```
      copying prody/tests/datafiles/msa_Cys_knot.fasta -> build/lib.linux-x86_64-cpython-39/prody/tests/datafiles
      running build_ext
      building 'prody.dynamics.rtbtools' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/prody
      creating build/temp.linux-x86_64-cpython-39/prody/dynamics
      gcc -pthread -B /home/rtakahashi/software/PoseBench/forks/DiffDock/DiffDock/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/rtakahashi/software/PoseBench/forks/DiffDock/DiffDock/include -fPIC -O2 -isystem /home/rtakahashi/software/PoseBench/forks/DiffDock/DiffDock/include -fPIC -I/tmp/pip-build-env-_tc6ayv0/overlay/lib/python3.9/site-packages/numpy/_core/include -I/home/rtakahashi/software/PoseBench/forks/DiffDock/DiffDock/include/python3.9 -c prody/dynamics/rtbtools.c -o build/temp.linux-x86_64-cpython-39/prody/dynamics/rtbtools.o
      In file included from /tmp/pip-build-env-_tc6ayv0/overlay/lib/python3.9/site-packages/numpy/_core/include/numpy/npy_common.h:376,
                       from /tmp/pip-build-env-_tc6ayv0/overlay/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarraytypes.h:4,
                       from /tmp/pip-build-env-_tc6ayv0/overlay/lib/python3.9/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                       from /tmp/pip-build-env-_tc6ayv0/overlay/lib/python3.9/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                       from prody/dynamics/rtbtools.c:9:
      prody/dynamics/rtbtools.c: In function ‘dblock_projections2’:
      prody/dynamics/rtbtools.c:422:17: error: expected identifier or ‘(’ before ‘__extension__’
        422 |   double **X, **I, **IC, *CM, *W, **A, **ISQT;
            |                 ^
      prody/dynamics/rtbtools.c:431:3: error: ‘CM’ undeclared (first use in this function)
        431 |   CM = dvector(1, 3);
            |   ^~
      prody/dynamics/rtbtools.c:431:3: note: each undeclared identifier is reported only once for each function it appears in
      prody/dynamics/rtbtools.c:432:5: error: lvalue required as left operand of assignment
        432 |   I = dmatrix(1, 3, 1, 3);
            |     ^
      prody/dynamics/rtbtools.c:433:3: error: ‘IC’ undeclared (first use in this function); did you mean ‘I’?
        433 |   IC = dmatrix(1, 3, 1, 3);
            |   ^~
            |   I
      prody/dynamics/rtbtools.c:434:3: error: ‘W’ undeclared (first use in this function)
        434 |   W = dvector(1, 3);
            |   ^
      prody/dynamics/rtbtools.c:435:3: error: ‘A’ undeclared (first use in this function)
        435 |   A = dmatrix(1, 3, 1, 3);
            |   ^
      prody/dynamics/rtbtools.c:436:3: error: ‘ISQT’ undeclared (first use in this function)
        436 |   ISQT = dmatrix(1, 3, 1, 3);
            |   ^~~~
      prody/dynamics/rtbtools.c:445:28: error: subscripted value is neither array nor pointer nor vector
        445 |       for(i=1; i<=3; i++) I[i][j] = 0.0;
            |                            ^
      prody/dynamics/rtbtools.c:481:10: error: subscripted value is neither array nor pointer nor vector
        481 |         I[i][i] += (dd - X[k][i] * X[k][i]);
            |          ^
      prody/dynamics/rtbtools.c:484:12: error: subscripted value is neither array nor pointer nor vector
        484 |           I[i][j] -= X[k][i]*X[k][j];
            |            ^
      prody/dynamics/rtbtools.c:485:12: error: subscripted value is neither array nor pointer nor vector
        485 |           I[j][i] = I[i][j];
            |            ^
      prody/dynamics/rtbtools.c:485:22: error: subscripted value is neither array nor pointer nor vector
        485 |           I[j][i] = I[i][j];
            |                      ^
      prody/dynamics/rtbtools.c:493:25: error: subscripted value is neither array nor pointer nor vector
        493 |               IC[i][j]=I[i][j];
            |                         ^
      prody/dynamics/rtbtools.c:548:16: error: incompatible type for argument 1 of ‘free_dmatrix’
        548 |   free_dmatrix(I, 1, 3, 1, 3);
            |                ^
            |                |
            |                complex float
      prody/dynamics/rtbtools.c:72:28: note: expected ‘double **’ but argument is of type ‘complex float’
         72 | void free_dmatrix(double **m, long nrl, long nrh, long ncl, long nch);
            |                   ~~~~~~~~~^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for prody
ERROR: Could not build wheels for prody, which is required to install pyproject.toml-based projects

failed

CondaEnvException: Pip failed
```

**Comment by amorehead** [comment] 2024-06-19 01:05
Hi, @rytakahashi. This `prody` installation error seems to be related to your local version of `gcc` or `c++`. Which version of these tools do you have locally installed? For example, on my end, I can successfully create the DiffDock Conda environment (using the command `mamba env create -f environments/diffdock_environment.yaml --prefix forks/DiffDock/DiffDock/`) with the following versions of `gcc` and `c++` locally installed:

```bash
(PoseBench) (base) [acmwhb@server PoseBench-Public]$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(PoseBench) (base) [acmwhb@server PoseBench-Public]$ c++ --version
c++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by amorehead** [comment] 2024-06-30 15:40
Hi, @rytakahashi. If you have any follow-up questions, please feel free to re-open this issue. In the meantime, I will be closing it.

**Closed by amorehead** 2024-06-30 15:40 UTC

**Comment by amorehead** [comment] 2024-07-05 15:51
Hi, @rytakahashi. To follow up on your `gcc` compilation error coming from ProDy, I was recently able to reproduce this issue on my end. In the new `v0.2.0` [release](https://github.com/BioinfoMachineLearning/PoseBench/releases/tag/v0.2.0), I have included a correction to the `PoseBench` Conda environment that fixes this original `gcc`/ProDy issue on my local machine.
